---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: seldon-local
  namespace: default    
rules:
- apiGroups: ["*"]
  resources:
  - deployments
  - services
  - pods
  verbs: ["*"]
- apiGroups:
  - machinelearning.seldon.io
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: seldon-crd
  namespace: default    
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seldon
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seldon
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: seldon-local
subjects:
  - kind: ServiceAccount
    name: seldon
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: seldon
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: seldon-crd
subjects:
  - kind: ServiceAccount
    name: seldon
    namespace: default

