application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  cluster_manager.image.name:
    description: Name of the image for the Seldon operator.
    type: string
    default: $REGISTRY/seldonio/seldon-core:$TAG
    x-google-marketplace:
      type: IMAGE
  engine.image.name:
    description: Name of the image for the Seldon service orchestrator.
    type: string
    default: $REGISTRY/seldonio/seldon-core/engine:$TAG
    x-google-marketplace:
      type: IMAGE
  apife.enabled:
    title: Install Seldon OAuth Gateway
    description: >-
      Create the Seldon OAUTH API gateway ingress. This will allow you
      to use OAuth authentication for your REST and gRPC endpoints for your
      machine learning deployments. Should be always set for now.
    type: boolean
    default: true
  apife.service_type:
    title: Service Type for Seldon OAuth Gateway
    description: >-
      Service type for Seldon API Gateway. Examples are NodePort or LoadBalancer.
    type: string
    default: NodePort
  apife.image.name:
    description: Name of the image for the seldon API gateway.
    type: string
    default: $REGISTRY/seldonio/seldon-core/apife:$TAG
    x-google-marketplace:
      type: IMAGE
  redis.image.name:
    description: Name of the image for redis.
    type: string
    default: $REGISTRY/seldonio/seldon-core/redis:$TAG
    x-google-marketplace:
      type: IMAGE
  rbac.service_account.name:
    title: Seldon Service Account.
    description: >-
      Name of a service account in the target namespace that
      has cluster-admin permissions. This is needed for the operator
      to create Seldon CRD and create namespaced resources.
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
required:
- name
- namespace
- cluster_manager.image.name
- engine.image.name
- apife.enabled
- apife.service_type
- apife.image.name
- redis.image.name
- rbac.service_account.name
